Gan team modal
cornerstone-rm/cornerstone-rm.github.io pull request #13
Opened 2016-09-16 18:43 UTC by garyanewsome

###### Create Modals on Team Page

Created a modal layout for the team page to replace the existing JavaScript "more" system.

2016-09-16 19:26 UTC, ninjapanzer commented
We need to find a way to store this information in a single place so we don't have to duplicate the content for name and title in two places. We also need some UX to inform people there is something to be clicked here

2016-09-16 19:26 UTC, ninjapanzer commented
I think it would be ok if it looked the way it did before and the modal open when you clicked the image or the `read more` link

2016-09-19 15:55 UTC, ninjapanzer commented on data/team.yaml
> +  - idn: "002"
Looking good. Whats the `idn` ?

2016-09-19 18:35 UTC, ninjapanzer commented on source/javascripts/all.js
> +    // var lesstext = "Show less";
Delete this comment

2016-09-19 18:35 UTC, ninjapanzer commented on source/javascripts/all.js
> +    // $(".morelink").click(function(){
Delete me

2016-09-19 18:35 UTC, ninjapanzer commented on source/javascripts/all.js
> +            // var html = c + '<span class="moreellipses">' + ellipsestext+ '&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a><
Delete me

2016-09-19 18:37 UTC, ninjapanzer commented on source/javascripts/all.js
> +
clean up trailing whitespace so there is only one new line at the end of the file

2016-09-19 18:37 UTC, ninjapanzer commented on source/javascripts/more.js
> +$(document).ready(function() {
Delete more.js since we don't need it

2016-09-19 18:37 UTC, ninjapanzer commented on source/meet.FAIL.html.erb
> +---
Lol delete

2016-09-19 18:38 UTC, ninjapanzer commented on source/meet.html.erb
> +</div>
👍

2016-09-19 18:38 UTC, ninjapanzer commented on source/team.html.erb
> +</div>
Needs a new line at the end of the file

2016-09-19 18:39 UTC, ninjapanzer commented on data/team.yaml
> +
new line at the end of the file

2016-09-19 18:41 UTC, ninjapanzer requested changes
Switch over the navigation so this links from the menu. Looks very good

2016-09-19 18:55 UTC, garyanewsome commented on data/team.yaml
> +  - idn: "002"
`idn` = id#, I needed a unique identifier to name the modal, so the proper modal lauches when clicked.

2016-09-19 19:02 UTC, aloya commented on data/team.yaml
> +    about: "Jackie brings more than 25 years’ experience from the pharmaceutical industry. She has received many awards and promotions including District Manager, Regional Director and Executive Dire
Could you remove the apostrophe after years.

2016-09-19 19:11 UTC, aloya commented on data/team.yaml
> +    about: "Joe Thoresen, Cornerstone’s founding consultant, became a licensed industrial/ organizational psychologist in 1976. After graduate school, he joined the team at Rohm and Haas, where he sp
Please remove the extra space after the slash so that it reads industrial/organizational. A zero-width space may be required. `&#8203;`

2016-09-19 19:45 UTC, ninjapanzer approved these changes

2016-09-19 19:48 UTC, merged